// flow-typed signature: 5f26466a6e4cd0f0a70b8b48c0cf2e1b
// flow-typed version: <<STUB>>/co-body_v^5.1.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co-body'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'co-body' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'co-body/lib/any' {
  declare module.exports: any;
}

declare module 'co-body/lib/form' {
  declare module.exports: any;
}

declare module 'co-body/lib/json' {
  declare module.exports: any;
}

declare module 'co-body/lib/text' {
  declare module.exports: any;
}

declare module 'co-body/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'co-body/index' {
  declare module.exports: $Exports<'co-body'>;
}
declare module 'co-body/index.js' {
  declare module.exports: $Exports<'co-body'>;
}
declare module 'co-body/lib/any.js' {
  declare module.exports: $Exports<'co-body/lib/any'>;
}
declare module 'co-body/lib/form.js' {
  declare module.exports: $Exports<'co-body/lib/form'>;
}
declare module 'co-body/lib/json.js' {
  declare module.exports: $Exports<'co-body/lib/json'>;
}
declare module 'co-body/lib/text.js' {
  declare module.exports: $Exports<'co-body/lib/text'>;
}
declare module 'co-body/lib/utils.js' {
  declare module.exports: $Exports<'co-body/lib/utils'>;
}
