// flow-typed signature: 74a0c3a6a61e9406cf2205afc82a5f48
// flow-typed version: <<STUB>>/isparta_v^4.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isparta'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isparta' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isparta/lib/cli/ArgParser' {
  declare module.exports: any;
}

declare module 'isparta/lib/cli/commands/cover' {
  declare module.exports: any;
}

declare module 'isparta/lib/cli/index' {
  declare module.exports: any;
}

declare module 'isparta/lib/instrumenter' {
  declare module.exports: any;
}

declare module 'isparta/lib/isparta' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isparta/lib/cli/ArgParser.js' {
  declare module.exports: $Exports<'isparta/lib/cli/ArgParser'>;
}
declare module 'isparta/lib/cli/commands/cover.js' {
  declare module.exports: $Exports<'isparta/lib/cli/commands/cover'>;
}
declare module 'isparta/lib/cli/index.js' {
  declare module.exports: $Exports<'isparta/lib/cli/index'>;
}
declare module 'isparta/lib/instrumenter.js' {
  declare module.exports: $Exports<'isparta/lib/instrumenter'>;
}
declare module 'isparta/lib/isparta.js' {
  declare module.exports: $Exports<'isparta/lib/isparta'>;
}
