// flow-typed signature: 966421434351bab3222a93157f8c8205
// flow-typed version: <<STUB>>/koa-session_v^5.8.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-session/lib/context' {
  declare module.exports: any;
}

declare module 'koa-session/lib/session' {
  declare module.exports: any;
}

declare module 'koa-session/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-session/index' {
  declare module.exports: $Exports<'koa-session'>;
}
declare module 'koa-session/index.js' {
  declare module.exports: $Exports<'koa-session'>;
}
declare module 'koa-session/lib/context.js' {
  declare module.exports: $Exports<'koa-session/lib/context'>;
}
declare module 'koa-session/lib/session.js' {
  declare module.exports: $Exports<'koa-session/lib/session'>;
}
declare module 'koa-session/lib/util.js' {
  declare module.exports: $Exports<'koa-session/lib/util'>;
}
