// flow-typed signature: b3057f3c83c0b2ef0f2518bc71acde3a
// flow-typed version: <<STUB>>/multer_v^1.3.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multer/lib/counter' {
  declare module.exports: any;
}

declare module 'multer/lib/file-appender' {
  declare module.exports: any;
}

declare module 'multer/lib/make-middleware' {
  declare module.exports: any;
}

declare module 'multer/lib/multer-error' {
  declare module.exports: any;
}

declare module 'multer/lib/remove-uploaded-files' {
  declare module.exports: any;
}

declare module 'multer/storage/disk' {
  declare module.exports: any;
}

declare module 'multer/storage/memory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multer/index' {
  declare module.exports: $Exports<'multer'>;
}
declare module 'multer/index.js' {
  declare module.exports: $Exports<'multer'>;
}
declare module 'multer/lib/counter.js' {
  declare module.exports: $Exports<'multer/lib/counter'>;
}
declare module 'multer/lib/file-appender.js' {
  declare module.exports: $Exports<'multer/lib/file-appender'>;
}
declare module 'multer/lib/make-middleware.js' {
  declare module.exports: $Exports<'multer/lib/make-middleware'>;
}
declare module 'multer/lib/multer-error.js' {
  declare module.exports: $Exports<'multer/lib/multer-error'>;
}
declare module 'multer/lib/remove-uploaded-files.js' {
  declare module.exports: $Exports<'multer/lib/remove-uploaded-files'>;
}
declare module 'multer/storage/disk.js' {
  declare module.exports: $Exports<'multer/storage/disk'>;
}
declare module 'multer/storage/memory.js' {
  declare module.exports: $Exports<'multer/storage/memory'>;
}
