// flow-typed signature: 97c96f600e855ea43ac3af880301d4a3
// flow-typed version: <<STUB>>/thenify_v^3.3.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'thenify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'thenify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'thenify/index' {
  declare module.exports: $Exports<'thenify'>;
}
declare module 'thenify/index.js' {
  declare module.exports: $Exports<'thenify'>;
}
